### ISSUE TITLE
Error starting up music.

### ISSUE THREAD

**Issue by Peyton2017** [bijij/mp3bot#2]
![capture](https://user-images.githubusercontent.com/28621717/33888749-cc6e8740-df02-11e7-92c2-2520a00ad02d.PNG)
It does this for anything I put in, and it never starts anything. If you know how to fix this, i'd appreciate help :), also if you wish to contact me fast my discord is: [ZorE#3169]
I have 99 incoming friend requests, if it hits 100, i'll look for you. Thanks, again.

**Comment by bijij** [comment]
Hi there I'm looking at your error you occurred when attempting to start mp3bot I would assume that the problem you're facing is due to the ID for the channel supplied in cogs/player/startup.json either being invalid or inaccessible by your bot. 

(I'm guessing the former as the ID to me looks too long to be a discord channel ID)

I'm planning on adding more detailed exception and error handling to the bot over the next week or so, so if we can't resolve your issue now. Hopefully we'll be able to by then.
